### PR TITLE
Add Black Friday 2019 packs plus more

### PR DESCRIPTION
**Pull request by TomJansen**
I made 2 packs because well, they're 2 packs

### CODE REVIEW

**Comment by TomJansen** [comment]
The AI and Human pack I typed out. The rest is from cah.frustratednerd.com

**Comment by TomJansen** [comment]
Okay this finishes my pull request. I went a little bit overboard with this one! Sorry! I had nothing better to do this Saturday. After you approve this pull request I can rebase this pr if you want.

BTW I did not add the scifi pack because one card contains a picture. If you decide how you want to add pictures I can add that pack as well.

**Comment by martinzuern** [comment]
Awesome work! @crhallberg is there a chance to get this merged? :)

**Comment by crhallberg** [comment]
Sorry I ignored this PR for so long! This IS incredible work and I'm merging it... with extreme gratitude... and a full heart... NOW!

**Pull request merged**
